
# SEO settings
title: "Think learn "
title2: "code" # default: ""
description: " A blog that focuses on technical writing on topics related to ML, Deep-learning and Computer Graphics"
keywords: "python, ml, deep learning, linux, gpu, openGL, cuda"
url: http://vetional.github.io/ # site url
#baseurl: "/vetional.github.io" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/vetional/vetional.github.io
disqus_shortname: "vetional"
twitter_username: "vetional"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Prateek Shrivastava"
  job      : "R&D Software Engineer"
  bio      : "I believe before someone builds a "super-bad robot," someone has to build a "mildly bad robot," and before that a "not-so-bad robot. To know more"
  thumb    : /images/author.jpg
  email    : prateek.shrvstv@gmail.com
  url      : http://vetional.github.io
  github   : http://github.com/vetional
  twitter  : http://twitter.com/vetional
  facebook : https://www.facebook.com/prateek.iitm
  linkedin : http://www.linkedin.com/in/prateek-shrivastava

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@vetional"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
